# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DOA_simulator.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 748)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_main = QtWidgets.QGridLayout()
        self.gridLayout_main.setObjectName("gridLayout_main")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider_source_DOA = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_source_DOA.setMaximum(360)
        self.horizontalSlider_source_DOA.setProperty("value", 90)
        self.horizontalSlider_source_DOA.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_source_DOA.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_source_DOA.setTickInterval(5)
        self.horizontalSlider_source_DOA.setObjectName("horizontalSlider_source_DOA")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_source_DOA)
        self.spinBox_DOA_value = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_DOA_value.setMaximum(360)
        self.spinBox_DOA_value.setProperty("value", 90)
        self.spinBox_DOA_value.setObjectName("spinBox_DOA_value")
        self.horizontalLayout_2.addWidget(self.spinBox_DOA_value)
        self.gridLayout_main.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.doubleSpinBox_ULA_d = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_ULA_d.setMaximum(10.0)
        self.doubleSpinBox_ULA_d.setSingleStep(0.1)
        self.doubleSpinBox_ULA_d.setProperty("value", 0.5)
        self.doubleSpinBox_ULA_d.setObjectName("doubleSpinBox_ULA_d")
        self.gridLayout_3.addWidget(self.doubleSpinBox_ULA_d, 2, 1, 1, 1)
        self.checkBox_en_ULA = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_en_ULA.setText("")
        self.checkBox_en_ULA.setObjectName("checkBox_en_ULA")
        self.gridLayout_3.addWidget(self.checkBox_en_ULA, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 0, 1, 1)
        self.checkBox_en_UCA = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_en_UCA.setText("")
        self.checkBox_en_UCA.setObjectName("checkBox_en_UCA")
        self.gridLayout_3.addWidget(self.checkBox_en_UCA, 3, 1, 1, 1)
        self.doubleSpinBox_UCA_r = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_UCA_r.setMaximum(10.0)
        self.doubleSpinBox_UCA_r.setSingleStep(0.1)
        self.doubleSpinBox_UCA_r.setProperty("value", 0.5)
        self.doubleSpinBox_UCA_r.setObjectName("doubleSpinBox_UCA_r")
        self.gridLayout_3.addWidget(self.doubleSpinBox_UCA_r, 4, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.spinBox_noa = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_noa.setMaximum(200)
        self.spinBox_noa.setProperty("value", 4)
        self.spinBox_noa.setObjectName("spinBox_noa")
        self.gridLayout_3.addWidget(self.spinBox_noa, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox_en_Bartlett = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_en_Bartlett.setText("")
        self.checkBox_en_Bartlett.setObjectName("checkBox_en_Bartlett")
        self.gridLayout_7.addWidget(self.checkBox_en_Bartlett, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 3, 0, 1, 1)
        self.checkBox_en_Capon = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_en_Capon.setText("")
        self.checkBox_en_Capon.setObjectName("checkBox_en_Capon")
        self.gridLayout_7.addWidget(self.checkBox_en_Capon, 1, 1, 1, 1)
        self.checkBox_en_MEM = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_en_MEM.setText("")
        self.checkBox_en_MEM.setObjectName("checkBox_en_MEM")
        self.gridLayout_7.addWidget(self.checkBox_en_MEM, 2, 1, 1, 1)
        self.checkBox_en_MUSIC = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_en_MUSIC.setText("")
        self.checkBox_en_MUSIC.setObjectName("checkBox_en_MUSIC")
        self.gridLayout_7.addWidget(self.checkBox_en_MUSIC, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 4, 0, 1, 1)
        self.checkBox_en_FBavg = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_en_FBavg.setText("")
        self.checkBox_en_FBavg.setObjectName("checkBox_en_FBavg")
        self.gridLayout_7.addWidget(self.checkBox_en_FBavg, 4, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_snr = QtWidgets.QLabel(self.groupBox)
        self.label_snr.setObjectName("label_snr")
        self.gridLayout_5.addWidget(self.label_snr, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        self.spinBox_snr_dB = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_snr_dB.setMinimum(-100)
        self.spinBox_snr_dB.setMaximum(100)
        self.spinBox_snr_dB.setProperty("value", 10)
        self.spinBox_snr_dB.setObjectName("spinBox_snr_dB")
        self.gridLayout_5.addWidget(self.spinBox_snr_dB, 0, 1, 1, 1)
        self.spinBox_sample_size = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_sample_size.setMinimum(3)
        self.spinBox_sample_size.setMaximum(25)
        self.spinBox_sample_size.setProperty("value", 10)
        self.spinBox_sample_size.setObjectName("spinBox_sample_size")
        self.gridLayout_5.addWidget(self.spinBox_sample_size, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox_mulitpath = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_mulitpath.setObjectName("spinBox_mulitpath")
        self.gridLayout_5.addWidget(self.spinBox_mulitpath, 2, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_main.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout_main.addWidget(self.comboBox, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.horizontalSlider_source_DOA.sliderMoved['int'].connect(self.spinBox_DOA_value.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Antenna configuration"))
        self.label_5.setText(_translate("MainWindow", "Enable UCA:"))
        self.label.setText(_translate("MainWindow", "Enable ULA:"))
        self.label_2.setText(_translate("MainWindow", "ULA spacing:"))
        self.label_4.setText(_translate("MainWindow", "UCA radius:"))
        self.label_12.setText(_translate("MainWindow", "Number of antennas:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "DOA options:"))
        self.label_9.setText(_translate("MainWindow", "MEM:"))
        self.label_6.setText(_translate("MainWindow", "Bartlett:"))
        self.label_7.setText(_translate("MainWindow", "Capon:"))
        self.label_8.setText(_translate("MainWindow", "MUSIC:"))
        self.label_10.setText(_translate("MainWindow", "FB-avg:"))
        self.groupBox.setTitle(_translate("MainWindow", "Simulation parameters"))
        self.label_snr.setText(_translate("MainWindow", "SNR [dB]:"))
        self.label_11.setText(_translate("MainWindow", "Sample size 2^x:"))
        self.label_3.setText(_translate("MainWindow", "Multipath:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Path 1"))
